name: build

on:
  push:
    # branches: main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Copy root certificate
      run: echo "${{ secrets.ROOT_CRT }}" > ./root_ca.crt

    - name: Build & Publish Docker Image
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        tags: akeb/php-fpm-${{ matrix.version }}:latest, akeb/php-fpm-${{ matrix.version }}:${{github.ref_name}}
        context: ./
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          PHP_VERSION=${{ matrix.version }}
